version: '3'

services:
  api-example:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-example
    environment:
      - DB_HOST=pg-example
      - REDIS_HOST=redis-example
    volumes:
      - ./application:/usr/server/application
    depends_on:
      - pg-example
      - redis-example
    ports:
      - 127.0.0.1:7000:7000
      - 127.0.0.1:7001:7001
    restart: always

  pg-example:
    image: postgres:14-alpine3.15
    container_name: pg-example
    environment:
      - POSTGRES_USER=marcus
      - POSTGRES_PASSWORD=marcus
      - POSTGRES_DB=application
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - 127.0.0.1:5432:5432
    restart: always

  redis-example:
    image: redis:6.2.6-alpine3.15
    container_name: redis-example
    command: redis-server --bind redis-example --requirepass 123456789
    volumes:
      - ./data/redis-example:/data
    ports:
      - 127.0.0.1:6380:6379
    restart: always

networks:
  default:
    name: api-example-network
